In [1]:
import os
import pandas as pd

dataset_path = "/home/lars/Documents/Datasets/StrawDI_image_regression/"

#This will effectively reset the pickle file to all NaN values - so that you can start labeling from scratch

df = pd.DataFrame(columns=["filename", "label"])
filename_list = [filename for filename in os.listdir(dataset_path + "images/") if filename.endswith(".png")]

df["filename"] = filename_list
df

          filename label
0       2085_6.png   NaN
1      1450_10.png   NaN
2       2298_3.png   NaN
3       2840_1.png   NaN
4       2396_6.png   NaN
...            ...   ...
17046   2867_3.png   NaN
17047   2212_8.png   NaN
17048   2839_4.png   NaN
17049    914_0.png   NaN
17050   2561_0.png   NaN

[17051 rows x 2 columns]

In [2]:
#Save the dataframe to a pickle file
df.to_pickle(dataset_path + "labeling_annotation.pkl")

In [3]:
#Test that we can open it and read the dataframe
df = pd.read_pickle(dataset_path + "labeling_annotation.pkl")
df.head(25)

       filename label
0    2085_6.png   NaN
1   1450_10.png   NaN
2    2298_3.png   NaN
3    2840_1.png   NaN
4    2396_6.png   NaN
5     617_6.png   NaN
6     487_6.png   NaN
7    1695_2.png   NaN
8    2470_2.png   NaN
9    1167_0.png   NaN
10   1980_3.png   NaN
11    964_0.png   NaN
12   2495_2.png   NaN
13   2382_5.png   NaN
14   1692_2.png   NaN
15   1051_4.png   NaN
16    870_1.png   NaN
17   3004_3.png   NaN
18     28_6.png   NaN
19   1873_1.png   NaN
20    528_3.png   NaN
21   1407_1.png   NaN
22    198_1.png   NaN
23    980_1.png   NaN
24   1783_3.png   NaN

In [4]:
#Get the first row where the label is NaN

#df[df["label"].isna()].head(1)

#Get the first filename where the label is NaN
test = df[df["label"].isna()].iloc[0]["filename"]
print(test)
print(type(test))

2085_6.png
<class 'str'>